-- Auto-generated by theme-dwm.sh
local scheme = "retro"

vim.api.nvim_create_autocmd("User", {
  pattern = "LazyDone",
  once = true,
  callback = function()
    pcall(vim.cmd, "colorscheme " .. scheme)
  end,
})
