
#!/usr/bin/env bash

# -------------------------------------------------
# Paths
# -------------------------------------------------
DWM_DIR="$HOME/.config/dwm"
THEME_DIR="$DWM_DIR/themes"
THEME_H="$DWM_DIR/theme.h"

WALLPAPER_DIR="$HOME/Pictures/wallpapers/theme"
INDEX_FILE="$HOME/.cache/theme-wallpaper-index"
CURRENT_THEME="$HOME/.cache/dwm-current-theme"

KITTY_THEME_DIR="$HOME/.config/kitty/themes"
ALACRITTY_THEME_DIR="$HOME/.config/alacritty/themes"

mkdir -p "$(dirname "$INDEX_FILE")"

# -------------------------------------------------
# Wallpaper rotation
# -------------------------------------------------
get_next_wallpaper() {
    local theme="$1"
    local files=() idx max

    while IFS= read -r -d '' f; do
        files+=("$f")
    done < <(
        find "$WALLPAPER_DIR" -type f \
            -regex ".*/${theme}-[0-9]+\.\(jpg\|png\)" \
            -print0 | sort -z -V
    )

    max=${#files[@]}
    (( max == 0 )) && return

    idx=$(grep "^$theme=" "$INDEX_FILE" 2>/dev/null | cut -d= -f2)
    [[ -z "$idx" ]] && idx=0
    idx=$(( (idx % max) + 1 ))

    sed -i "/^$theme=/d" "$INDEX_FILE"
    echo "$theme=$idx" >> "$INDEX_FILE"

    echo "${files[$((idx - 1))]}"
}

# -------------------------------------------------
# Xresources (for bar / other tools)
# -------------------------------------------------
apply_xresources() {
    xrdb -merge <<EOF
dwm.bg: $(grep col_cyan  "$THEME_H" | awk '{print $NF}' | tr -d '";')
dwm.fg: $(grep col_gray3 "$THEME_H" | awk '{print $NF}' | tr -d '";')
EOF
}

# -------------------------------------------------
# Apply theme
# -------------------------------------------------


apply_theme() {
    local theme="$1"
    local src="$THEME_DIR/$theme.h"

    if [[ -z "$theme" ]]; then
        notify-send "❌ No theme provided"
        exit 1
    fi

    if [[ ! -f "$src" ]]; then
        notify-send "❌ Theme not found: $theme"
        exit 1
    fi

    echo "$theme" > "$CURRENT_THEME"

    cp "$src" "$THEME_H"
    apply_xresources

    if [[ -n "$2" && -f "$2" ]]; then
        nitrogen --set-zoom-fill "$2" --save
    else
        wp="$(get_next_wallpaper "$theme")"
        [[ -n "$wp" ]] && nitrogen --set-zoom-fill "$wp" --save
    fi

    cd "$DWM_DIR" || exit 1
    sudo make clean install
    pkill -HUP dwm

    if [[ -f "$KITTY_THEME_DIR/$theme.conf" ]]; then
        ln -sf "$KITTY_THEME_DIR/$theme.conf" "$KITTY_THEME_DIR/current.conf"
        kitty @ set-colors --all "$KITTY_THEME_DIR/current.conf" 2>/dev/null
    fi

    if [[ -f "$ALACRITTY_THEME_DIR/$theme.toml" ]]; then
        ln -sf "$ALACRITTY_THEME_DIR/$theme.toml" "$ALACRITTY_THEME_DIR/current.toml"
        pkill -USR1 alacritty 2>/dev/null
    fi

    NVIM_CS_FILE="$HOME/.config/nvim/lua/siliwho/core/colorscheme.lua"

    case "$theme" in
      blackwhite)  NVIM_CS="cyberdream" ;;
      gruvbox)     NVIM_CS="retro" ;;
      tokyo)       NVIM_CS="tokyodark" ;;
      everforest)  NVIM_CS="tokyonight" ;;
      nord)        NVIM_CS="nord" ;;
      *)           NVIM_CS="tokyodark" ;;
    esac

cat > "$NVIM_CS_FILE" <<EOF
-- Auto-generated by theme-dwm.sh
local scheme = "$NVIM_CS"

vim.api.nvim_create_autocmd("User", {
  pattern = "LazyDone",
  once = true,
  callback = function()
    pcall(vim.cmd, "colorscheme " .. scheme)
  end,
})
EOF

    notify-send "Theme switched to $theme"
}



# -------------------------------------------------
# Entry point
# -------------------------------------------------
apply_theme "$1" "$2"

